services:
  app:
    build: .
    ports:
      - "55555:55555"
      - "55556:55556"
      - "55557:55557"
      - "64444:64444"
      - "55558:55558"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=Ab9919Ab@
      - DB_NAME=db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Ab9919Ab@
      MYSQL_DATABASE: db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: